---
- name: 'Verify'
  hosts: 'all'
  tasks:
    - name: 'Check if service is running'
      ansible.builtin.service:
        name: 'bitbucket'
        state: 'started'
      check_mode: true

    - name: 'Check if WebUI is reachable'
      ansible.builtin.uri:
        url: 'http://localhost:7990/setup'
        return_content: true
        method: 'GET'
      register: 'bitbucket_webui'
      failed_when: "'Atlassian Bitbucket' not in bitbucket_webui['content']"
